ZSHA_BASE=~/.dotfiles/zsh
source $ZSHA_BASE/antigen/antigen.zsh

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=vim
export BAT_THEME=GitHub
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

UNAME=`uname`

if [[ $UNAME == 'Darwin' ]]; then
  antigen bundle brew
fi

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-completions src

antigen bundle tmux
antigen bundle vim
antigen bundle fancy-ctrl-z

antigen bundle git
antigen bundle git-prompt
antigen bundle gitignore

# antigen bundle history
antigen bundle autojump

antigen bundle node
antigen bundle npm
antigen bundle yarn

antigen bundle golang
antigen bundle pip

antigen bundle mvn
antigen bundle scala
antigen bundle sbt
antigen bundle gradle

antigen bundle vagrant
antigen bundle docker
antigen bundle docker-compose
antigen bundle kubectl
antigen bundle terraform

# antigen bundle ytools

export FZF_BASE=/usr/local/opt/fzf/
antigen bundle fzf

export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true
antigen bundle lukechilds/zsh-nvm

antigen theme philips

antigen apply

mdcd () {
  mkdir -p -- "$1" && cd -P -- "$1"
}
export mdcd
clone () {
  git clone "$1" && cd "$(basename "$1" .git)"
}
export clone

export RPROMPT=''

export AWS_PROFILE=federate
export AWS_DEFAULT_REGION=us-east-2

export SSH_AUTH_SOCK=~/.yubiagent/sock

export PATH="/usr/local/sbin:$PATH"
export PATH="/Users/mshauneu/Bin:$PATH"
export PATH="/Users/mshauneu/go/bin:$PATH"

alias t="trans -t ru"
alias tp="trans -t ru -speak"
alias cat="bat -p"

#source <(kubectl completion zsh)
#alias kubectl="kubecolor --light-background"
#compdef kubecolor=kubectl

hash -d d=~/Downloads
hash -d m=~/Music
hash -d p=~/Projects
hash -d mp=~/Projects/my
hash -d tp=~/Projects/tmp
hash -d wp=~/Projects/vm/tnv

export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/Users/mshauneu/Opt/git-fuzzy/bin:$PATH"

[ -s "/Users/mshauneu/.jabba/jabba.sh" ] && source "/Users/mshauneu/.jabba/jabba.sh"
jabba use adopt@1.8.0-252
