ZSHA_BASE=~/.dotfiles/zsh
source $ZSHA_BASE/antigen/antigen.zsh

# Ensure languages are set
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Ensure editor is set
export EDITOR=vim

# OS Detection
UNAME=`uname`

# Fallback info
CURRENT_OS='Linux'
if [[ $UNAME == 'Darwin' ]]; then
  CURRENT_OS='OS X'
fi

antigen bundle zsh-users/zsh-syntax-highlighting
#antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src

antigen use oh-my-zsh

antigen bundle tmux
antigen bundle git
antigen bundle git-prompt
antigen bundle gitignore

antigen bundle golang
antigen bundle pip

antigen bundle history
antigen bundle autojump

antigen bundle node
antigen bundle npm

antigen bundle mvn
antigen bundle scala
antigen bundle sbt
antigen bundle gradle

antigen bundle vagrant
antigen bundle docker
antigen bundle docker-compose
antigen bundle kubectl
antigen bundle terraform
antigen bundle heroku

antigen theme jreese

if [[ $CURRENT_OS == 'OS X' ]]; then
  antigen bundle brew
  antigen bundle brew-cask
elif [[ $CURRENT_OS == 'Linux' ]]; then
  # None so far...
fi

antigen apply

# Use Ctrl-Z to switch back to Vim
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

bindkey "^X\x7f" backward-kill-line
bindkey "^X^_" redo

mdcd () {
  mkdir -p -- "$1" &&
    cd -P -- "$1"
}
export mdcd

export PATH="/usr/local/sbin:$PATH"
export PATH="~/Bin:$PATH"
export PATH="~/go/bin:$PATH"
export PATH="/usr/local/opt/node@10/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

SSH_AUTH_SOCK=~/.yubiagent/sock
#alias load_key="ssh-add -s /usr/local/lib/opensc-pkcs11.so"
#alias unload_key="ssh-add -e /usr/local/lib/opensc-pkcs11.so"
